FROM digrouz/alpine-s6:latest
LABEL maintainer="DI GREGORIO Nicolas <ndigrego@ndg-consulting.tech>"

ARG NEXUS_VERSION='3.86.2-01'
ARG NEXUS_DOWNLOAD_URL="https://download.sonatype.com/nexus/3/sonatype-nexus-repository-${NEXUS_VERSION}-assembly.zip"

# Environment variables
ENV NEXUS_VERSION="${NEXUS_VERSION}" \
    NEXUS_DOWNLOAD_URL="${NEXUS_DOWNLOAD_URL}"\
    SONATYPE_DIR="/opt/sonatype" \
    NEXUS_DATA="/nexus-data" \
    NEXUS_WORK="/nexus-work" \
    NEXUS_CONTEXT='' 
ENV NEXUS_HOME="${SONATYPE_DIR}/nexus" \
    SONATYPE_WORK="${SONATYPE_DIR}/sonatype-work" \
    INSTALL4J_ADD_VM_PARAMS="-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"

COPY root /

# Install Application
RUN set -x && \
    usermod -m -d ${SONATYPE_DIR} appuser && \
    apk --no-cache upgrade && \
    apk add --no-cache --virtual=build-deps \
      curl \
      unzip \
    && \
    apk add --no-cache --virtual=run-deps \
      openjdk17 \
    && \
    curl --fail --silent --location --retry 3 ${NEXUS_DOWNLOAD_URL} -o /tmp/sonatype-nexus-repository-${NEXUS_VERSION}-assembly.zip && \
    mkdir -p ${SONATYPE_DIR} ${NEXUS_WORK} ${NEXUS_DATA} && \
    unzip /tmp/sonatype-nexus-repository-${NEXUS_VERSION}-assembly.zip -d /tmp && \
    mv /tmp/nexus-${NEXUS_VERSION} ${NEXUS_HOME} && \
    ln -snf ${NEXUS_WORK} ${SONATYPE_WORK} && \
    sed -e '/^nexus-context/ s:$:${NEXUS_CONTEXT}:' -i ${NEXUS_HOME}/etc/nexus-default.properties && \
    chown -R appuser:appuser ${SONATYPE_DIR} ${NEXUS_HOME} ${SONATYPE_WORK} ${NEXUS_WORK} ${NEXUS_DATA} && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*
    
# Expose volumes
VOLUME ["${NEXUS_DATA}"]

# Expose ports
EXPOSE 8081
